services:
  firstwebapplication:
    image: ${DOCKER_REGISTRY-}firstwebapplication
    build:
      context: .
      dockerfile: FirstWebApplication/Dockerfile
    ports:
      - "5001:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DatabaseConnection=Server=mariadbcontainer;Port=3306;Database=KartverketDB;User=root;Password=Mammaerbest1;
    depends_on:
      mariadbcontainer:
        condition: service_healthy

  mariadbcontainer:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: Mammaerbest1
      MYSQL_DATABASE: KartverketDB
    ports:
      - "3307:3306"
    volumes:
      - mariadbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      
volumes:
    mariadbdata:
