version: "3.8"

services:
  firstwebapplication:
    image: ${DOCKER_REGISTRY-}firstwebapplication
    build:
      context: .
      dockerfile: FirstWebApplication/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DatabaseConnection=Server=mariadbcontainer;Database=KartverketDB;User=root;Password=Mammaerbest1;
    depends_on:
      - mariadbcontainer

  mariadbcontainer:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mammaerbest1
      MYSQL_DATABASE: KartverketDB
    ports:
      - "3307:3306"
    volumes:
      - mariadbdata:/var/lib/mysql

volumes:
  mariadbdata: